#!/usr/bin/env bash

START_DATE=2017-01-01
END_DATE=2018-05-30

./coinmarketcap_usd_history.py bitcoin $START_DATE $END_DATE > bitcoin.csv
./coinmarketcap_usd_history.py ethereum $START_DATE $END_DATE > ethereum.csv
./coinmarketcap_usd_history.py ripple $START_DATE $END_DATE > ripple.csv
./coinmarketcap_usd_history.py bitcoin-cash $START_DATE $END_DATE > bitcoin-cash.csv
./coinmarketcap_usd_history.py eos $START_DATE $END_DATE > eos.csv
./coinmarketcap_usd_history.py litecoin $START_DATE $END_DATE > litecoin.csv
./coinmarketcap_usd_history.py cardano $START_DATE $END_DATE > cardano.csv
./coinmarketcap_usd_history.py stellar $START_DATE $END_DATE > stellar.csv
./coinmarketcap_usd_history.py iota $START_DATE $END_DATE > iota.csv
./coinmarketcap_usd_history.py tron $START_DATE $END_DATE > tron.csv
./coinmarketcap_usd_history.py neo $START_DATE $END_DATE > neo.csv
./coinmarketcap_usd_history.py tether $START_DATE $END_DATE > tether.csv
./coinmarketcap_usd_history.py monero $START_DATE $END_DATE > monero.csv
./coinmarketcap_usd_history.py dash $START_DATE $END_DATE > dash.csv
./coinmarketcap_usd_history.py nem $START_DATE $END_DATE > nem.csv
./coinmarketcap_usd_history.py vechain $START_DATE $END_DATE > vechain.csv
./coinmarketcap_usd_history.py ethereum-classic $START_DATE $END_DATE > ethereum-classic.csv
./coinmarketcap_usd_history.py binance-coin $START_DATE $END_DATE > binance-coin.csv
./coinmarketcap_usd_history.py qtum $START_DATE $END_DATE > qtum.csv
./coinmarketcap_usd_history.py bytecoin-bcn $START_DATE $END_DATE > bytecoin-bcn.csv
./coinmarketcap_usd_history.py omisego $START_DATE $END_DATE > omisego.csv
./coinmarketcap_usd_history.py zcash $START_DATE $END_DATE > zcash.csv
./coinmarketcap_usd_history.py icon $START_DATE $END_DATE > icon.csv
./coinmarketcap_usd_history.py lisk $START_DATE $END_DATE > lisk.csv
./coinmarketcap_usd_history.py ontology $START_DATE $END_DATE > ontology.csv
./coinmarketcap_usd_history.py zilliqa $START_DATE $END_DATE > zilliqa.csv
./coinmarketcap_usd_history.py aeternity $START_DATE $END_DATE > aeternity.csv
./coinmarketcap_usd_history.py bitcoin-gold $START_DATE $END_DATE > bitcoin-gold.csv
./coinmarketcap_usd_history.py decred $START_DATE $END_DATE > decred.csv
./coinmarketcap_usd_history.py 0x $START_DATE $END_DATE > 0x.csv
./coinmarketcap_usd_history.py bytom $START_DATE $END_DATE > bytom.csv
./coinmarketcap_usd_history.py steem $START_DATE $END_DATE > steem.csv
./coinmarketcap_usd_history.py verge $START_DATE $END_DATE > verge.csv
./coinmarketcap_usd_history.py nano $START_DATE $END_DATE > nano.csv
./coinmarketcap_usd_history.py bitshares $START_DATE $END_DATE > bitshares.csv
./coinmarketcap_usd_history.py siacoin $START_DATE $END_DATE > siacoin.csv
./coinmarketcap_usd_history.py populous $START_DATE $END_DATE > populous.csv
./coinmarketcap_usd_history.py rchain $START_DATE $END_DATE > rchain.csv
./coinmarketcap_usd_history.py wanchain $START_DATE $END_DATE > wanchain.csv
./coinmarketcap_usd_history.py maker $START_DATE $END_DATE > maker.csv
./coinmarketcap_usd_history.py bitcoin-private $START_DATE $END_DATE > bitcoin-private.csv
./coinmarketcap_usd_history.py bitcoin-diamond $START_DATE $END_DATE > bitcoin-diamond.csv
./coinmarketcap_usd_history.py golem-network-tokens $START_DATE $END_DATE > golem-network-tokens.csv
./coinmarketcap_usd_history.py stratis $START_DATE $END_DATE > stratis.csv
./coinmarketcap_usd_history.py augur $START_DATE $END_DATE > augur.csv
./coinmarketcap_usd_history.py waves $START_DATE $END_DATE > waves.csv
./coinmarketcap_usd_history.py dogecoin $START_DATE $END_DATE > dogecoin.csv
./coinmarketcap_usd_history.py mixin $START_DATE $END_DATE > mixin.csv
./coinmarketcap_usd_history.py waykichain $START_DATE $END_DATE > waykichain.csv
./coinmarketcap_usd_history.py waltonchain $START_DATE $END_DATE > waltonchain.csv
./coinmarketcap_usd_history.py iostoken $START_DATE $END_DATE > iostoken.csv
./coinmarketcap_usd_history.py digibyte $START_DATE $END_DATE > digibyte.csv
./coinmarketcap_usd_history.py status $START_DATE $END_DATE > status.csv
./coinmarketcap_usd_history.py hshare $START_DATE $END_DATE > hshare.csv
./coinmarketcap_usd_history.py aion $START_DATE $END_DATE > aion.csv
./coinmarketcap_usd_history.py nebulas-token $START_DATE $END_DATE > nebulas-token.csv
./coinmarketcap_usd_history.py loopring $START_DATE $END_DATE > loopring.csv
./coinmarketcap_usd_history.py basic-attention-token $START_DATE $END_DATE > basic-attention-token.csv
./coinmarketcap_usd_history.py digixdao $START_DATE $END_DATE > digixdao.csv
./coinmarketcap_usd_history.py cybermiles $START_DATE $END_DATE > cybermiles.csv
./coinmarketcap_usd_history.py komodo $START_DATE $END_DATE > komodo.csv
./coinmarketcap_usd_history.py ardor $START_DATE $END_DATE > ardor.csv
./coinmarketcap_usd_history.py aelf $START_DATE $END_DATE > aelf.csv
./coinmarketcap_usd_history.py ark $START_DATE $END_DATE > ark.csv
./coinmarketcap_usd_history.py pivx $START_DATE $END_DATE > pivx.csv
./coinmarketcap_usd_history.py polymath-network $START_DATE $END_DATE > polymath-network.csv
./coinmarketcap_usd_history.py dentacoin $START_DATE $END_DATE > dentacoin.csv
./coinmarketcap_usd_history.py loom-network $START_DATE $END_DATE > loom-network.csv
./coinmarketcap_usd_history.py gxchain $START_DATE $END_DATE > gxchain.csv
./coinmarketcap_usd_history.py monacoin $START_DATE $END_DATE > monacoin.csv
./coinmarketcap_usd_history.py bancor $START_DATE $END_DATE > bancor.csv
./coinmarketcap_usd_history.py cortex $START_DATE $END_DATE > cortex.csv
./coinmarketcap_usd_history.py skycoin $START_DATE $END_DATE > skycoin.csv
./coinmarketcap_usd_history.py cryptonex $START_DATE $END_DATE > cryptonex.csv
./coinmarketcap_usd_history.py maidsafecoin $START_DATE $END_DATE > maidsafecoin.csv
./coinmarketcap_usd_history.py elastos $START_DATE $END_DATE > elastos.csv
./coinmarketcap_usd_history.py syscoin $START_DATE $END_DATE > syscoin.csv
./coinmarketcap_usd_history.py huobi-token $START_DATE $END_DATE > huobi-token.csv
./coinmarketcap_usd_history.py reddcoin $START_DATE $END_DATE > reddcoin.csv
./coinmarketcap_usd_history.py gas $START_DATE $END_DATE > gas.csv
./coinmarketcap_usd_history.py mybit-token $START_DATE $END_DATE > mybit-token.csv
./coinmarketcap_usd_history.py qash $START_DATE $END_DATE > qash.csv
./coinmarketcap_usd_history.py fusion $START_DATE $END_DATE > fusion.csv
./coinmarketcap_usd_history.py mithril $START_DATE $END_DATE > mithril.csv
./coinmarketcap_usd_history.py ethos $START_DATE $END_DATE > ethos.csv
./coinmarketcap_usd_history.py kyber-network $START_DATE $END_DATE > kyber-network.csv
./coinmarketcap_usd_history.py funfair $START_DATE $END_DATE > funfair.csv
./coinmarketcap_usd_history.py veritaseum $START_DATE $END_DATE > veritaseum.csv
./coinmarketcap_usd_history.py electroneum $START_DATE $END_DATE > electroneum.csv
./coinmarketcap_usd_history.py substratum $START_DATE $END_DATE > substratum.csv
./coinmarketcap_usd_history.py centrality $START_DATE $END_DATE > centrality.csv
./coinmarketcap_usd_history.py nexus $START_DATE $END_DATE > nexus.csv
./coinmarketcap_usd_history.py rlc $START_DATE $END_DATE > rlc.csv
./coinmarketcap_usd_history.py dragonchain $START_DATE $END_DATE > dragonchain.csv
./coinmarketcap_usd_history.py enigma-project $START_DATE $END_DATE > enigma-project.csv
./coinmarketcap_usd_history.py nuls $START_DATE $END_DATE > nuls.csv
./coinmarketcap_usd_history.py zcoin $START_DATE $END_DATE > zcoin.csv
./coinmarketcap_usd_history.py dropil $START_DATE $END_DATE > dropil.csv
./coinmarketcap_usd_history.py holo $START_DATE $END_DATE > holo.csv
./coinmarketcap_usd_history.py all-sports $START_DATE $END_DATE > all-sports.csv
