#!/usr/bin/env bash

START_DATE=2017-01-01
END_DATE=2018-05-30

./coinmarketcap_usd_history.py bitcoin $START_DATE $END_DATE > bitcoin-$END_DATE.csv
./coinmarketcap_usd_history.py ethereum $START_DATE $END_DATE > ethereum-$END_DATE.csv
./coinmarketcap_usd_history.py ripple $START_DATE $END_DATE > ripple-$END_DATE.csv
./coinmarketcap_usd_history.py bitcoin-cash $START_DATE $END_DATE > bitcoin-cash-$END_DATE.csv
./coinmarketcap_usd_history.py eos $START_DATE $END_DATE > eos-$END_DATE.csv
./coinmarketcap_usd_history.py litecoin $START_DATE $END_DATE > litecoin-$END_DATE.csv
./coinmarketcap_usd_history.py cardano $START_DATE $END_DATE > cardano-$END_DATE.csv
./coinmarketcap_usd_history.py stellar $START_DATE $END_DATE > stellar-$END_DATE.csv
./coinmarketcap_usd_history.py iota $START_DATE $END_DATE > iota-$END_DATE.csv
./coinmarketcap_usd_history.py tron $START_DATE $END_DATE > tron-$END_DATE.csv
./coinmarketcap_usd_history.py neo $START_DATE $END_DATE > neo-$END_DATE.csv
./coinmarketcap_usd_history.py tether $START_DATE $END_DATE > tether-$END_DATE.csv
./coinmarketcap_usd_history.py monero $START_DATE $END_DATE > monero-$END_DATE.csv
./coinmarketcap_usd_history.py dash $START_DATE $END_DATE > dash-$END_DATE.csv
./coinmarketcap_usd_history.py nem $START_DATE $END_DATE > nem-$END_DATE.csv
./coinmarketcap_usd_history.py vechain $START_DATE $END_DATE > vechain-$END_DATE.csv
./coinmarketcap_usd_history.py ethereum-classic $START_DATE $END_DATE > ethereum-classic-$END_DATE.csv
./coinmarketcap_usd_history.py binance-coin $START_DATE $END_DATE > binance-coin-$END_DATE.csv
./coinmarketcap_usd_history.py qtum $START_DATE $END_DATE > qtum-$END_DATE.csv
./coinmarketcap_usd_history.py bytecoin-bcn $START_DATE $END_DATE > bytecoin-bcn-$END_DATE.csv
./coinmarketcap_usd_history.py omisego $START_DATE $END_DATE > omisego-$END_DATE.csv
./coinmarketcap_usd_history.py zcash $START_DATE $END_DATE > zcash-$END_DATE.csv
./coinmarketcap_usd_history.py icon $START_DATE $END_DATE > icon-$END_DATE.csv
./coinmarketcap_usd_history.py lisk $START_DATE $END_DATE > lisk-$END_DATE.csv
./coinmarketcap_usd_history.py ontology $START_DATE $END_DATE > ontology-$END_DATE.csv
./coinmarketcap_usd_history.py zilliqa $START_DATE $END_DATE > zilliqa-$END_DATE.csv
./coinmarketcap_usd_history.py aeternity $START_DATE $END_DATE > aeternity-$END_DATE.csv
./coinmarketcap_usd_history.py bitcoin-gold $START_DATE $END_DATE > bitcoin-gold-$END_DATE.csv
./coinmarketcap_usd_history.py decred $START_DATE $END_DATE > decred-$END_DATE.csv
./coinmarketcap_usd_history.py 0x $START_DATE $END_DATE > 0x-$END_DATE.csv
./coinmarketcap_usd_history.py bytom $START_DATE $END_DATE > bytom-$END_DATE.csv
./coinmarketcap_usd_history.py steem $START_DATE $END_DATE > steem-$END_DATE.csv
./coinmarketcap_usd_history.py verge $START_DATE $END_DATE > verge-$END_DATE.csv
./coinmarketcap_usd_history.py nano $START_DATE $END_DATE > nano-$END_DATE.csv
./coinmarketcap_usd_history.py bitshares $START_DATE $END_DATE > bitshares-$END_DATE.csv
./coinmarketcap_usd_history.py siacoin $START_DATE $END_DATE > siacoin-$END_DATE.csv
./coinmarketcap_usd_history.py populous $START_DATE $END_DATE > populous-$END_DATE.csv
./coinmarketcap_usd_history.py rchain $START_DATE $END_DATE > rchain-$END_DATE.csv
./coinmarketcap_usd_history.py wanchain $START_DATE $END_DATE > wanchain-$END_DATE.csv
./coinmarketcap_usd_history.py maker $START_DATE $END_DATE > maker-$END_DATE.csv
./coinmarketcap_usd_history.py bitcoin-private $START_DATE $END_DATE > bitcoin-private-$END_DATE.csv
./coinmarketcap_usd_history.py bitcoin-diamond $START_DATE $END_DATE > bitcoin-diamond-$END_DATE.csv
./coinmarketcap_usd_history.py golem-network-tokens $START_DATE $END_DATE > golem-network-tokens-$END_DATE.csv
./coinmarketcap_usd_history.py stratis $START_DATE $END_DATE > stratis-$END_DATE.csv
./coinmarketcap_usd_history.py augur $START_DATE $END_DATE > augur-$END_DATE.csv
./coinmarketcap_usd_history.py waves $START_DATE $END_DATE > waves-$END_DATE.csv
./coinmarketcap_usd_history.py dogecoin $START_DATE $END_DATE > dogecoin-$END_DATE.csv
./coinmarketcap_usd_history.py mixin $START_DATE $END_DATE > mixin-$END_DATE.csv
./coinmarketcap_usd_history.py waykichain $START_DATE $END_DATE > waykichain-$END_DATE.csv
./coinmarketcap_usd_history.py waltonchain $START_DATE $END_DATE > waltonchain-$END_DATE.csv
./coinmarketcap_usd_history.py iostoken $START_DATE $END_DATE > iostoken-$END_DATE.csv
./coinmarketcap_usd_history.py digibyte $START_DATE $END_DATE > digibyte-$END_DATE.csv
./coinmarketcap_usd_history.py status $START_DATE $END_DATE > status-$END_DATE.csv
./coinmarketcap_usd_history.py hshare $START_DATE $END_DATE > hshare-$END_DATE.csv
./coinmarketcap_usd_history.py aion $START_DATE $END_DATE > aion-$END_DATE.csv
./coinmarketcap_usd_history.py nebulas-token $START_DATE $END_DATE > nebulas-token-$END_DATE.csv
./coinmarketcap_usd_history.py loopring $START_DATE $END_DATE > loopring-$END_DATE.csv
./coinmarketcap_usd_history.py basic-attention-token $START_DATE $END_DATE > basic-attention-token-$END_DATE.csv
./coinmarketcap_usd_history.py digixdao $START_DATE $END_DATE > digixdao-$END_DATE.csv
./coinmarketcap_usd_history.py cybermiles $START_DATE $END_DATE > cybermiles-$END_DATE.csv
./coinmarketcap_usd_history.py komodo $START_DATE $END_DATE > komodo-$END_DATE.csv
./coinmarketcap_usd_history.py ardor $START_DATE $END_DATE > ardor-$END_DATE.csv
./coinmarketcap_usd_history.py aelf $START_DATE $END_DATE > aelf-$END_DATE.csv
./coinmarketcap_usd_history.py ark $START_DATE $END_DATE > ark-$END_DATE.csv
./coinmarketcap_usd_history.py pivx $START_DATE $END_DATE > pivx-$END_DATE.csv
./coinmarketcap_usd_history.py polymath-network $START_DATE $END_DATE > polymath-network-$END_DATE.csv
./coinmarketcap_usd_history.py dentacoin $START_DATE $END_DATE > dentacoin-$END_DATE.csv
./coinmarketcap_usd_history.py loom-network $START_DATE $END_DATE > loom-network-$END_DATE.csv
./coinmarketcap_usd_history.py gxchain $START_DATE $END_DATE > gxchain-$END_DATE.csv
./coinmarketcap_usd_history.py monacoin $START_DATE $END_DATE > monacoin-$END_DATE.csv
./coinmarketcap_usd_history.py bancor $START_DATE $END_DATE > bancor-$END_DATE.csv
./coinmarketcap_usd_history.py cortex $START_DATE $END_DATE > cortex-$END_DATE.csv
./coinmarketcap_usd_history.py skycoin $START_DATE $END_DATE > skycoin-$END_DATE.csv
./coinmarketcap_usd_history.py cryptonex $START_DATE $END_DATE > cryptonex-$END_DATE.csv
./coinmarketcap_usd_history.py maidsafecoin $START_DATE $END_DATE > maidsafecoin-$END_DATE.csv
./coinmarketcap_usd_history.py elastos $START_DATE $END_DATE > elastos-$END_DATE.csv
./coinmarketcap_usd_history.py syscoin $START_DATE $END_DATE > syscoin-$END_DATE.csv
./coinmarketcap_usd_history.py huobi-token $START_DATE $END_DATE > huobi-token-$END_DATE.csv
./coinmarketcap_usd_history.py reddcoin $START_DATE $END_DATE > reddcoin-$END_DATE.csv
./coinmarketcap_usd_history.py gas $START_DATE $END_DATE > gas-$END_DATE.csv
./coinmarketcap_usd_history.py mybit-token $START_DATE $END_DATE > mybit-token-$END_DATE.csv
./coinmarketcap_usd_history.py qash $START_DATE $END_DATE > qash-$END_DATE.csv
./coinmarketcap_usd_history.py fusion $START_DATE $END_DATE > fusion-$END_DATE.csv
./coinmarketcap_usd_history.py mithril $START_DATE $END_DATE > mithril-$END_DATE.csv
./coinmarketcap_usd_history.py ethos $START_DATE $END_DATE > ethos-$END_DATE.csv
./coinmarketcap_usd_history.py kyber-network $START_DATE $END_DATE > kyber-network-$END_DATE.csv
./coinmarketcap_usd_history.py funfair $START_DATE $END_DATE > funfair-$END_DATE.csv
./coinmarketcap_usd_history.py veritaseum $START_DATE $END_DATE > veritaseum-$END_DATE.csv
./coinmarketcap_usd_history.py electroneum $START_DATE $END_DATE > electroneum-$END_DATE.csv
./coinmarketcap_usd_history.py substratum $START_DATE $END_DATE > substratum-$END_DATE.csv
./coinmarketcap_usd_history.py centrality $START_DATE $END_DATE > centrality-$END_DATE.csv
./coinmarketcap_usd_history.py nexus $START_DATE $END_DATE > nexus-$END_DATE.csv
./coinmarketcap_usd_history.py rlc $START_DATE $END_DATE > rlc-$END_DATE.csv
./coinmarketcap_usd_history.py dragonchain $START_DATE $END_DATE > dragonchain-$END_DATE.csv
./coinmarketcap_usd_history.py enigma-project $START_DATE $END_DATE > enigma-project-$END_DATE.csv
./coinmarketcap_usd_history.py nuls $START_DATE $END_DATE > nuls-$END_DATE.csv
./coinmarketcap_usd_history.py zcoin $START_DATE $END_DATE > zcoin-$END_DATE.csv
./coinmarketcap_usd_history.py dropil $START_DATE $END_DATE > dropil-$END_DATE.csv
./coinmarketcap_usd_history.py holo $START_DATE $END_DATE > holo-$END_DATE.csv
./coinmarketcap_usd_history.py all-sports $START_DATE $END_DATE > all-sports-$END_DATE.csv
